#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-jaxb-impl
Version  : 2.2.3.1
Release  : 4
URL      : https://repo1.maven.org/maven2/com/sun/xml/bind/jaxb-impl/2.2.3-1/jaxb-impl-2.2.3-1.jar
Source0  : https://repo1.maven.org/maven2/com/sun/xml/bind/jaxb-impl/2.2.3-1/jaxb-impl-2.2.3-1.jar
Source1  : https://repo1.maven.org/maven2/com/sun/xml/bind/jaxb-impl/2.1.12/jaxb-impl-2.1.12.jar
Source2  : https://repo1.maven.org/maven2/com/sun/xml/bind/jaxb-impl/2.1.12/jaxb-impl-2.1.12.pom
Source3  : https://repo1.maven.org/maven2/com/sun/xml/bind/jaxb-impl/2.2.3-1/jaxb-impl-2.2.3-1.jar
Source4  : https://repo1.maven.org/maven2/com/sun/xml/bind/jaxb-impl/2.2.3-1/jaxb-impl-2.2.3-1.pom
Source5  : https://repo1.maven.org/maven2/com/sun/xml/bind/jaxb-impl/2.2.3-1/jaxb-impl-2.2.3-1.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : CDDL-1.1 GPL-2.0-only
Requires: mvn-jaxb-impl-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-jaxb-impl package.
Group: Data

%description data
data components for the mvn-jaxb-impl package.


%prep
%setup -q -n META-INF

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/sun/xml/bind/jaxb-impl/2.2.3-1
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/com/sun/xml/bind/jaxb-impl/2.2.3-1/jaxb-impl-2.2.3-1.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/sun/xml/bind/jaxb-impl/2.1.12
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/com/sun/xml/bind/jaxb-impl/2.1.12/jaxb-impl-2.1.12.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/sun/xml/bind/jaxb-impl/2.1.12
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/com/sun/xml/bind/jaxb-impl/2.1.12/jaxb-impl-2.1.12.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/sun/xml/bind/jaxb-impl/2.2.3-1
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/com/sun/xml/bind/jaxb-impl/2.2.3-1/jaxb-impl-2.2.3-1.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/sun/xml/bind/jaxb-impl/2.2.3-1
cp %{SOURCE4} %{buildroot}/usr/share/java/.m2/repository/com/sun/xml/bind/jaxb-impl/2.2.3-1/jaxb-impl-2.2.3-1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/sun/xml/bind/jaxb-impl/2.2.3-1
cp %{SOURCE5} %{buildroot}/usr/share/java/.m2/repository/com/sun/xml/bind/jaxb-impl/2.2.3-1/jaxb-impl-2.2.3-1.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/com/sun/xml/bind/jaxb-impl/2.1.12/jaxb-impl-2.1.12.jar
/usr/share/java/.m2/repository/com/sun/xml/bind/jaxb-impl/2.1.12/jaxb-impl-2.1.12.pom
/usr/share/java/.m2/repository/com/sun/xml/bind/jaxb-impl/2.2.3-1/jaxb-impl-2.2.3-1.jar
/usr/share/java/.m2/repository/com/sun/xml/bind/jaxb-impl/2.2.3-1/jaxb-impl-2.2.3-1.pom
